# Публичные каналы для парсинга
# Формат: {'channel': 'username', 'threads': [id1, id2] или None, 'exclude_threads': [id1]}

CHANNELS = [
    # Ветки конкретных тредов
    {'channel': 'Ananastolki', 'threads': [40766, 24645, 34919, 41074, 41327, 39662], 'exclude_threads': []},
    {'channel': 'hsegg', 'threads': [3626, 4757, 27056, 9391], 'exclude_threads': [25125, 1, 3610]},
    {'channel': 'Inspector_party', 'threads': [583], 'exclude_threads': []},

    # Полные каналы
    {'channel': 'msc_mafia', 'threads': None, 'exclude_threads': []},
    {'channel': 'qbangerr', 'threads': None, 'exclude_threads': []},
    {'channel': 'kylt_org', 'threads': None, 'exclude_threads': []},
    {'channel': 'more_transformations', 'threads': None, 'exclude_threads': []},
    {'channel': 'mafiaOnlineLST', 'threads': None, 'exclude_threads': []},
    {'channel': 'msk4free', 'threads': None, 'exclude_threads': []},
    {'channel': 'moscowafishi', 'threads': None, 'exclude_threads': []},
    {'channel': 'skiboardAFISHA', 'threads': None, 'exclude_threads': []},
    {'channel': 'TimepadRU', 'threads': None, 'exclude_threads': []},
    {'channel': 'free_concerts', 'threads': None, 'exclude_threads': []},
    {'channel': 'skolkovosocialdance', 'threads': None, 'exclude_threads': []},
    {'channel': 'teatrsport', 'threads': None, 'exclude_threads': []},
    {'channel': 'skiboardSALE', 'threads': None, 'exclude_threads': []},
    {'channel': 'gnosis_shop', 'threads': None, 'exclude_threads': []},
    {'channel': 'mus_lampa', 'threads': None, 'exclude_threads': []},
    {'channel': 'art_vrsk', 'threads': None, 'exclude_threads': []},
    {'channel': 'Rassvet_original', 'threads': None, 'exclude_threads': []},
    {'channel': 'moscowsee', 'threads': None, 'exclude_threads': []},
    {'channel': 'sis_terss', 'threads': None, 'exclude_threads': []},
    {'channel': 'Nastolochnaya', 'threads': None, 'exclude_threads': []},
    {'channel': 'lovefishki', 'threads': None, 'exclude_threads': []},
    {'channel': 'Game_Mos', 'threads': None, 'exclude_threads': []},
    {'channel': 'blagosfera_space', 'threads': None, 'exclude_threads': []},
    {'channel': 'freimancuts', 'threads': None, 'exclude_threads': []},
    {'channel': 'gppromo', 'threads': None, 'exclude_threads': []},
    {'channel': 'migingame', 'threads': None, 'exclude_threads': []},
    {'channel': 'rgubru', 'threads': None, 'exclude_threads': []},
    {'channel': 'mosigra', 'threads': None, 'exclude_threads': []},
    {'channel': 'hyperion_book', 'threads': None, 'exclude_threads': []},
    {'channel': 'gagarinlib', 'threads': None, 'exclude_threads': []},
    {'channel': 'youthdmoscow', 'threads': None, 'exclude_threads': []},
    {'channel': 'oriental_centre', 'threads': None, 'exclude_threads': []},
    {'channel': 'childbibl20', 'threads': None, 'exclude_threads': []},
    {'channel': 'trcnora', 'threads': None, 'exclude_threads': []},
    {'channel': 'lynxofcthulhu', 'threads': None, 'exclude_threads': []},
    {'channel': 'pia_2018', 'threads': None, 'exclude_threads': []},
    {'channel': 'dreamer487_drafts', 'threads': None, 'exclude_threads': []},
    {'channel': 'ladnooenglish', 'threads': None, 'exclude_threads': []},
    {'channel': 'knizhnykub', 'threads': None, 'exclude_threads': []},
    {'channel': 'biblio100', 'threads': None, 'exclude_threads': []},
    {'channel': 'ladnospot', 'threads': None, 'exclude_threads': []},
    {'channel': 'setrumochnyh', 'threads': None, 'exclude_threads': []},
    {'channel': 'board_games_preobr', 'threads': None, 'exclude_threads': []},
    {'channel': 'nashhyperionskijmajong', 'threads': None, 'exclude_threads': []},
    {'channel': 'gamesjewish', 'threads': None, 'exclude_threads': []},
    {'channel': 'Zilplay', 'threads': None, 'exclude_threads': []},
    {'channel': 'nastolkidolgoprudniy', 'threads': None, 'exclude_threads': []},
    {'channel': 'pushkinmoslib', 'threads': None, 'exclude_threads': []},
    {'channel': 'krtn_dwizh', 'threads': None, 'exclude_threads': []},
    {'channel': 'dostlibrary', 'threads': None, 'exclude_threads': []},
    {'channel': 'mskaafisha', 'threads': None, 'exclude_threads': []},
    {'channel': 'afishamska', 'threads': None, 'exclude_threads': []},
    {'channel': 'kids_msk_afisha', 'threads': None, 'exclude_threads': []},
    {'channel': 'kulturauao', 'threads': None, 'exclude_threads': []},
    {'channel': 'bgconnection', 'threads': None, 'exclude_threads': []},
    {'channel': 'museum15kop', 'threads': None, 'exclude_threads': []},
    {'channel': 'msk1000ru', 'threads': None, 'exclude_threads': []},
    {'channel': 'irfest', 'threads': None, 'exclude_threads': []},
    {'channel': 'hobby_games', 'threads': None, 'exclude_threads': []},
    {'channel': 'bauman_reading_club', 'threads': None, 'exclude_threads': []},
    {'channel': 'ligaimprova', 'threads': None, 'exclude_threads': []},
    {'channel': 'sumerki_cuddles', 'threads': None, 'exclude_threads': []},
    {'channel': 'disgustingmen', 'threads': None, 'exclude_threads': []},
    {'channel': 'prostpolitika', 'threads': None, 'exclude_threads': []},
    {'channel': 'freeskidos', 'threads': None, 'exclude_threads': []},
    {'channel': 'idemmskdeti', 'threads': None, 'exclude_threads': []},
    {'channel': 'circumstance_hse', 'threads': None, 'exclude_threads': []},
    {'channel': 'oruchmsk', 'threads': None, 'exclude_threads': []},
    {'channel': 'moscowcalling', 'threads': None, 'exclude_threads': []},
    {'channel': 'artsvao_team', 'threads': None, 'exclude_threads': []},
    {'channel': 'rogozhkaru', 'threads': None, 'exclude_threads': []},
    {'channel': 'terragames', 'threads': None, 'exclude_threads': []},
    {'channel': 'leelanr', 'threads': None, 'exclude_threads': []},
]

# Каналы недоступны (приватные) — бот сообщит об этом в логах
UNAVAILABLE_CHANNELS = [
    't.me/c/2677068816/12',
    't.me/c/2354376415/1',
    't.me/c/2354376415/10',
    't.me/c/1131701294/50042',
    't.me/c/1131701294/50050',
    't.me/c/2169653082',
    't.me/c/1755880511',
    'moscowzoo.ru/assets/img/tg.svg',  # не Telegram
]
